### ISSUE TITLE
DOes not work in latest ios

### ISSUE THREAD

**Issue by sandeepsahoogirik** [willmcpo/body-scroll-lock#25] opened 2018-07-05 20:24 UTC
Hi
This does not seems to work in Iphone safari - latest ios. 
We have a similar code and it seems to have the same issue.
When I try this on my laptop it works without any issue and so does my code but in iOS it does not seem to work.
Kind Regards
Sandeep

**Comment by sandeepsahoogirik** [comment] 2018-07-05 21:28
Got it to work  I replaced the following
$(document).on('touchmove', function (e) {
if (e.target.tagName == "CANVAS") {
		        e.preventDefault();
		    }
}
with 
window.addEventListener('touchmove', function (e) {			
		    if (e.target.tagName == "CANVAS") {
		        e.preventDefault();
		    }
 }, { passive: false });

The passive false is imp.

Basically the call is 

window.addEventListener('touchmove', func, { passive: false })

**Comment by SergeyLukashov** [comment] 2018-07-09 08:00
Hi,
I faced the same issue for latest iOS. Even `{ passive: false }` for event listener doesn't seem to work to me. Is there another workaround?

**Comment by sandeepsahoogirik** [comment] 2018-07-09 11:07
Hi 
Please note the only way I was able to get this to work was to add the event listener on the window object
window.addEventListener

It does not work where I use the "document"

Kind Regards
Sandeep

**Comment by SergeyLukashov** [comment] 2018-07-09 13:10
Thanks Sandeep! That may be the cause - will try it.

**Comment by skarakash** [comment] 2018-07-25 09:12
so is this fixed for ios 11> ?

**Comment by sandeepsahoogirik** [comment] 2018-07-25 09:15
It did for our project. 
You can check the pages we are using this on

https://www.oka.com/cushion-arranger/

Kind Regards
Sandeep

**Comment by willmcpo** [comment] 2018-07-30 22:15
Closing issue as it appears the latest ios > 11 fixed the issue.

**Closed by willmcpo** 2018-07-30 22:15 UTC

**Comment by willmcpo** [comment] 2018-07-30 22:28
@inkquery not without some work on your end.

To do what you want, you first need to download npm/yarn =).  But after that, just fork/clone the repo, then run `yarn build`. Then grab the file with the compiled javascript code, make some mods to expose the logic globally....

As its open source, feel free to do above, as long as credit is provided where due =)
