### ISSUE TITLE
Doesn't work on iOS

### ISSUE THREAD

**Issue by sairus2k** [willmcpo/body-scroll-lock#177] opened 2020-05-07 10:26 UTC
The video was recorded on simulator iPhone 8 iOS 13.4
The same behavior is on device iPhone 5s iOS 12.4

![ezgif-3-e00cc8f4b1d4](https://user-images.githubusercontent.com/1106887/81283684-3b69de00-9087-11ea-8fa2-21987af39489.gif)

**Comment by knynkwl** [comment] 2020-05-07 13:03
+1 getting this issue as well.

**Comment by hacknug** [comment] 2020-05-15 19:03
Works fine for me on iOS 13.5 (17F5065a)

**Comment by ryanirilli** [comment] 2020-05-21 14:50
See these lines in the src, you must provide a target element for this to work in iOS Safari. After I added a target it works for me.

https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L147-L149

**Comment by eni9889** [comment] 2020-05-29 19:36
I have a target element and it is still not working on ios 13.5 simulator

**Comment by virginie-p** [comment] 2020-06-02 14:56
Doesn't work on iOs either (Safari), the body doesn't have an inline style added (overflow: hidden;) but on Chrome (desktop) this inline style is here.

**Comment by diachedelic** [comment] 2020-06-04 06:00
I have tested `body-scroll-lock@3.0.3` in the iOS simulator running 13.5, with and without fixed elements, and it appears to work fine. Are you sure it is an issue introduced by iOS 13.5? Can you test with 13.4.1 @eni9889 ? Please supply a minimal reproduction if possible.

`overflow: hidden` is not added on iOS @virginie-p , instead the strategy is to block `touchmove` events.

**Comment by metinsut** [comment] 2020-06-15 11:53
Same problem: bsl-3.0.3, IOS-13.5
bodyScrollLock.esm.js

line 210,211

Error -> Attempted to assign to readonly property.

**Comment by diachedelic** [comment] 2020-06-16 01:27
@metinsut are you sure you are passing a DOM element to `enableScrollLock`? See https://github.com/willmcpo/body-scroll-lock/issues/110

**Comment by metinsut** [comment] 2020-06-16 09:23
> @metinsut are you sure you are passing a DOM element to `enableScrollLock`? See #110

Uhh sorry my bad 🤦, I am so sorry for being careless.

**Comment by diachedelic** [comment] 2020-06-17 00:24
It's OK, there should be a better error message.

**Comment by shurinskiy** [comment] 2020-08-28 05:48
Yes, this does not work on ipad ios 12.4.8

**Comment by diachedelic** [comment] 2020-08-28 06:09
@shurinskiy  bodyscrollock.now.sh uses a very out of date version of the library

**Comment by shurinskiy** [comment] 2020-09-01 03:34
> @shurinskiy bodyscrollock.now.sh uses a very out of date version of the library

@diachedelic Too bad, it was a very handy thing. Can you advise what you can use instead?

**Comment by pomacs-store** [comment] 2020-09-01 03:40
@shurinskiy the Readme has recently been updated with latest library version and new Demo links.

**Comment by diachedelic** [comment] 2020-09-01 03:41
@shurinskiy this has just been fixed in #194

**Closed by diachedelic** 2020-09-01 03:41 UTC
