### ISSUE TITLE
iPad OS 13.3.1 does not lock body scroll for "Request Desktop Website"

### ISSUE THREAD

**Issue by ejoflo** [willmcpo/body-scroll-lock#163] opened 2020-03-14 03:10 UTC
When testing body scroll lock on an iPad Pro using iPad OS 13, the user is still able to scroll the parent element. In my case, I am loading a Modal. The background (parent) is still scrollable. 

If I "Request Mobile Site" body scroll lock works again. I also noticed that while in "Request Desktop Website" mode, the scrolling becomes glitched and element's z-index of modal and body sometimes overlap.

**Comment by diachedelic** [comment] 2020-03-14 05:58
Duplicate of #156 , which will be fixed in an upcoming release

**Closed by diachedelic** 2020-03-14 05:58 UTC
