### ISSUE TITLE
disableBodyScroll: content scrolls back to top

### ISSUE THREAD

**Issue by apolopena** [willmcpo/body-scroll-lock#182] opened 2020-06-15 22:03 UTC
I am using React and the current scroll position is lost when `disableBodyScroll` is called.
In other words when I disable scrolling using `bodyScrollLock.disableBodyScroll` the the content locks properly  **_but_** it also autoscrolls back to the top of the page.
I am using https://cdn.jsdelivr.net/npm/body-scroll-lock@3.0.3/lib/bodyScrollLock.min.js

I have recreated the issue on [CodePen here](https://codepen.io/ApoloPena/pen/yLeabpV).
I am expecting the current scroll position to be preserved.

**Comment by benjaminhollissc** [comment] 2020-06-15 22:27
I'm seeing this as well - it may have changed with a recent update.

**Comment by mrlss** [comment] 2020-07-10 11:51
Hello. Any updates regarding this issue? Experiencing same issue in static site project.

**Comment by diachedelic** [comment] 2020-07-14 01:10
@mrlss are you using gatsby? more info here: https://github.com/willmcpo/body-scroll-lock/issues/154

**Comment by S4n3L** [comment] 2020-07-15 08:38
I had the same issue, and I found a solution for it here: https://css-tricks.com/prevent-page-scrolling-when-a-modal-is-open/

And here is how I implemented finally. I ended up not using the body-scroll-lock package at all because this solution worked me on IOS too. I never tested it on Android though.

When you open your modal:

    if (isOpen) {
      document.querySelector("html").style.scrollBehavior = "unset"
      const tmpScrollY = window.scrollY
      setScrollPosition(window.scrollY)
      document.body.style.position = "fixed"
      document.body.style.top = `-${tmpScrollY}px`
    }

And when you close it:

if (onClosed) {
        document.body.style.position = ""
        document.body.style.top = ""
        window.scrollTo(0, scrollPosition)
        document.querySelector("html").style.scrollBehavior = "smooth"
        setIsClosing(false)
        onClosed()
      }

The scroll behavior part only necessary if you have in-page routes/anchors you scrollTo, and you want to keep that behavior when the modal isn't open.

**Comment by alekslario** [comment] 2020-07-15 22:34
Same issue here. Had to fallback to `overscroll-behavior:contain` that is supported by most modern browsers. It does has it's own quirks but at least it doesn't reset scroll position.

**Comment by reidterror** [comment] 2020-07-22 07:55
I've been having the same issue. Running Nextjs with body-scroll-lock 3.0.3. 
my component is set up with ref forwarding.

    import {disableBodyScroll, clearAllBodyScrollLocks} from 'body-scroll-lock';
    let component2;
    class Component1 extends Component {
        toggleComponent2 = () => {
            if (// logic to show element) {
                disableBodyScroll(component2);
            } else {
                cleraAllBodyScrollLocks();
            }
        }

        render() {
            return (
                <div forwardedRef={ref => component2 = ref}> content </div>
            )
        }
    }

**Comment by jmikrut** [comment] 2020-09-27 14:47
I am experiencing the same, with a custom non-SSR React app (no Next, no Gatsby). I feel like it wasn't always this way though and that this may have been introduced at some point over the last year.

Any update here?

**Comment by diachedelic** [comment] 2020-09-28 00:42
@jmikrut could you please try reverting #189 and/or #199, and see if that fixes the issue?

**Comment by jmikrut** [comment] 2020-09-28 00:48
You know what? I think my issue (and maybe others in this thread) was caused by CSS being applied to the `html` and / or `body` elements. 

I had the following CSS in my app:

```css
html {
  overflow-y: scroll;
}

html, body {
  height: 100%;
}
```

I removed them and the problem is gone. I suggest others in this thread check for similar results!

**Comment by jtomaszewski** [comment] 2021-01-03 17:15
> my issue (and maybe others in this thread) was caused by CSS being applied to the html and / or body elements. - https://github.com/willmcpo/body-scroll-lock/issues/182#issuecomment-699714361

Same here.

I guess body-scroll-lock could warn in the console if `html` / `body` elements has those styles on themselves. (Or alter the styles - by removing `height: 100%` if body is larger than the screen.)

**Comment by mindnektar** [comment] 2021-07-28 14:36
I've figured out what the problem is and made a pull request: https://github.com/willmcpo/body-scroll-lock/pull/228

**Comment by apolopena** [comment] 2021-07-28 18:47
> I had the same problem with the latest version (`4.0.0-beta.0`).
> 
> By using `^3.1.5`, this problem has been solved.

This did not solve the problem for me in the chrome web browser

**Comment by apolopena** [comment] 2021-07-28 18:49
> I've figured out what the problem is and made a pull request: #228

Looks like this should solve this issue in a web browser as well?

**Comment by mindnektar** [comment] 2021-07-29 09:15
I personally didn't have this issue in a web browser, and the `setPositionFixed` function will only be called for iOS devices.

**Closed** 2021-08-14 01:16 UTC

**Comment by snax4a** [comment] 2021-10-07 09:29
I confirm that downgrading to `^3.1.5` fixes this issue

**Comment by devsangwoo** [comment] 2021-10-19 07:32
still have issue

**Comment by kfw9257** [comment] 2021-12-20 15:01
still dealing with this issue even after downgrading. I was able to get it working using the solution @S4n3L provided.

**Comment by AnhTuanOkeT** [comment] 2022-03-22 10:34
Yeah downgrading to `3.1.5` fix this issue

**Comment by h-jennings** [comment] 2022-03-28 15:16
Downgrading to `@3.1.5` fixed this issue for me as well

**Comment by rick-liruixin** [comment] 2023-04-04 11:03
They stopped maintenance. I had to work it out myself, using the same approach, with a new version of typeScript. And fix the original problem, available for everyone to use. 
```
npm i body-scroll-lock-upgrade
```

**Comment by DevonRoepke** [comment] 2023-06-28 22:49
> They stopped maintenance. I had to work it out myself, using the same approach, with a new version of typeScript. And fix the original problem, available for everyone to use. 
> 
> ```
> 
> npm i body-scroll-lock-upgrade
> 
> ```

Thank you for the fix! This worked for me.
