### ISSUE TITLE
enableBodyScroll doesn't enable scroll

### ISSUE THREAD

**Issue by An-Cu** [willmcpo/body-scroll-lock#90] opened 2019-01-28 10:11 UTC
`enableBodyScroll` doesn't enable scroll in situation `disableBodyScroll` was required (n+1)-times and `enableBodyScroll` n-times.
`enableBodyScroll` and `disableBodyScroll` was required without arguments.

To reproduce the issue try the next sequence of function requiring:
`disableBodyScroll()`
`disableBodyScroll()`
`enableBodyScroll()`
as result `overflow: hidden` styles in `<body>` still  persist.

I already have prepared commit to fix this issue

**Comment by hacknug** [comment] 2019-05-06 10:53
@willmcpo anything I can do to help get the PR merged? You can replicate the issue by clicking twice `disableBodyScroll` and then `enableBodyScroll` on [your demo link](https://bodyscrolllock.now.sh/).

**Comment by SeanSilke** [comment] 2019-06-03 12:58
The same with me. I have modal inside modal. And [this line](https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L232) evaluated too false because  locks length is > 1.

**Comment by diachedelic** [comment] 2019-06-03 13:06
@SeanSilke if you close one modal and still have one open, the body should still be locked, right?

**Comment by SeanSilke** [comment] 2019-06-10 15:46
@diachedelic  Yes. My problem is with unlocking body scroll.

**Comment by kossel** [comment] 2019-06-14 21:37
another situation that causes the `overflow:hidden` from body is if the target element is not longer exits. eg. unmounted

**Comment by willmcpo** [comment] 2019-06-16 07:20
i started reviewing this one

**Comment by willmcpo** [comment] 2019-06-16 19:58
Why would you ever call disableScroll on the same target element?

**Comment by kossel** [comment] 2019-06-16 20:02
I have similar problem but when the targetElement doesn't exist anymore, eg. it unmounted or something the body's overflow would never be removed.

**Comment by willmcpo** [comment] 2019-06-16 20:30
Can you describe more of your use case?

**Comment by kossel** [comment] 2019-06-16 21:40
yes, please see this [codesandbox ](https://codesandbox.io/s/youthful-ardinghelli-y4por) I created to reproduce it.

it's a very very slim down version of what I'm doing, basically for modal, we offer the option of "unmount  content when close" so when the `isOpen` become false, the scroll target element is not longer exits, 
and this line returns false
https://github.com/willmcpo/body-scroll-lock/blob/master/src/bodyScrollLock.js#L232
since targetElement is null.

**Comment by SeanSilke** [comment] 2019-06-25 08:27
@willmcpo  wrote `Why would you ever call disableScroll on the same target element?`
In our case we call for popup from popup.
The `disableScroll` mast be Idempotent, number of calls should not affect result.

**Comment by willmcpo** [comment] 2019-06-25 11:42
@seansilke

Sure. The pull request to fix this needs to make an amendment then we can merge.

**Comment by willmcpo** [comment] 2019-06-27 23:28
Merged fix

**Closed by willmcpo** 2019-06-27 23:28 UTC
