### ISSUE TITLE
Demo Not working on Chrome for iOS

### ISSUE THREAD

**Issue by stemsmit** [willmcpo/body-scroll-lock#5] opened 2018-02-26 20:11 UTC
When I was testing the demo site in Chrome for iOS it appears body scroll lock has no effect.

Tested Devices:
iPhone 8 iOS 11.1 Chrome
iPhone 6 iOS 10 Chrome
iPhone 6S Plus iOS 9 Chrome

**Comment by willmcpo** [comment] 2018-02-28 10:42
Hi @stemsmit - I'll look into it and get back to you shortly.

**Comment by willmcpo** [comment] 2018-03-03 00:54
@bill-feng @stemsmit the issue is fixed in the latest release

**Closed by willmcpo** 2018-03-03 00:54 UTC
